# ============================================================================
# 自动化测试框架核心配置文件
# ============================================================================
# 说明：
# 1. 此文件只包含框架的核心配置
# 2. 环境特定配置在 environments.yaml 中设置
# 3. 测试执行和数据配置在 test_settings.yaml 中设置
# ============================================================================

# 测试类型：api(仅API测试) / web(仅Web测试) / both(API和Web测试)
test_type: "both"

# ============================================================================
# 并发执行配置
# ============================================================================
execution:
  concurrent:
    enabled: true # 是否启用并发执行
    max_workers: 4 # 最大工作线程数
    timeout: 120 # 单个测试用例超时时间（秒）

    # 不同测试类型的并发配置
    api:
      enabled: true # API测试并发开关
      max_workers: 3 # API测试最大线程数
      timeout: 120 # API测试超时时间

    web:
      enabled: true # Web测试并发开关
      max_workers: 2 # Web测试最大线程数（浏览器资源消耗大）
      timeout: 300 # Web测试超时时间
      headless: true # 并发时使用无头浏览器

    mixed:
      enabled: true # 混合测试并发开关
      max_workers: 4 # 混合测试最大线程数
      timeout: 300 # 混合测试超时时间

# ============================================================================
# 测试报告配置
# ============================================================================
report:
  type: "pytest-html" # allure / pytest-html / both
  clean_history: false
  keep_last: 5
  allure_serve: false

# ============================================================================
# 消息通知配置
# ============================================================================
notification:
  enabled: false
  types: [] # feishu / email / wechat / dingtalk
  report_url: ""

# ============================================================================
# 日志配置
# ============================================================================
logging:
  level: "INFO"
  file_level: "DEBUG"
  console_level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  rotation: "100 MB"
  retention: "30 days"
  compression: "zip"

# ============================================================================
# 数据库基础配置
# ============================================================================
database:
  enabled: false
  defaults:
    type: "mysql"
    charset: "utf8mb4"
    pool:
      min_connections: 1
      max_connections: 10
      max_idle_time: 300
